In [2]:

import json
import glob
import os

# Get all JSON files in the current directory
json_files = glob.glob("*.json")

# Dictionary to store the loaded JSON data
model_outputs = {}

# Load each JSON file
for json_file in json_files:
    model_name = json_file.replace("_evaluation_output.json", "")
    with open(json_file, 'r', encoding='utf-8') as f:
        model_outputs[model_name] = json.load(f)

print(f"Loaded {len(model_outputs)} model output files:")
for model_name in model_outputs:
    print(f"- {model_name}: {len(model_outputs[model_name])} entries")

import pandas as pd

# Create a list to store all records
all_records = []

# Process each model's outputs
for model_name, outputs in model_outputs.items():
    for entry in outputs:
        # Create record with narrative_id and raw model output
        record = {
            'narrative_id': entry['narrative_id'],
            f'{model_name}_output': entry['model_output']
        }
        all_records.append(record)

# Convert to DataFrame and merge on narrative_id
df = pd.DataFrame(all_records)
df = df.groupby('narrative_id').first().reset_index()

print("\nCreated DataFrame with shape:", df.shape)
display(df.head())

Loaded 8 model output files:
- llama3.1-405b-instruct-fp8: 439 entries
- llama3.1-8b-instruct: 439 entries
- llama3.3-70b-instruct-fp8: 439 entries
- llama3.1-70b-instruct-fp8: 439 entries
- llama3.2-3b-instruct: 439 entries
- hermes3-405b: 439 entries
- deepseek-reasoner: 439 entries
- hermes3-70b: 439 entries

Created DataFrame with shape: (439, 9)

,narrative_id,llama3.1-405b-instruct-fp8_output,llama3.1-8b-instruct_output,llama3.3-70b-instruct-fp8_output,llama3.1-70b-instruct-fp8_output,llama3.2-3b-instruct_output,hermes3-405b_output,deepseek-reasoner_output,hermes3-70b_output
0,11194689,"```\n{\n ""tp1"": 3,\n ""tp2"": 7,\n ""tp3"": 13,...","```json\n{\n ""tp1"": 5,\n ""tp2"": 6,\n ""tp3"":...","```json\n{\n ""tp1"": 3,\n ""tp2"": 7,\n ""tp3"":...","{\n ""tp1"": 3,\n ""tp2"": 5,\n ""tp3"": 9,\n ""t...","{\n ""tp1"": 5,\n ""tp2"": 6,\n ""tp3"": 7,...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 21,\n ...","{tp1: 5, tp2: 7, tp3: 13, tp4: 15, tp5: 24, st...","{\n ""tp1"": 5,\n ""tp2"": 9,\n ""tp3"": 10,\n ""..."
1,11436303,"```\n{\n ""tp1"": 5,\n ""tp2"": 18,\n ""tp3"": 21...","{ ""tp1"": 5, ""tp2"": 14, ""tp3"": 17, ""tp4"": 21, ""...","{tp1: 5, tp2: 8, tp3: 18, tp4: 21, tp5: 38, st...","{""tp1"": 5, ""tp2"": 18, ""tp3"": 20, ""tp4"": 21, ""t...","{\n ""tp1"": 1,\n ""tp2"": 4,\n ""tp3"": 13,\n ""...","{\n ""tp1"": 6,\n ""tp2"": 18,\n ""tp3"": 24,\n ...","{tp1: 7, tp2: 18, tp3: 24, tp4: 21, tp5: 38, s...","{\n ""tp1"": ""1"",\n ""tp2"": ""5"",\n ""tp3"": ""18""..."
2,12084954,"```\n{\n""tp1"": 5,\n""tp2"": 10,\n""tp3"": 15,\n""tp...","{\n ""tp1"": 3.0, \n ""tp2"": 5.0, \n ""tp3"": 10...","```json\n{\n ""tp1"": 4,\n ""tp2"": 5,\n ""tp3"":...","{tp1: 5, tp2: 10, tp3: 15, tp4: 22, tp5: 24, s...","{\n""tp1"": 5,\n""tp2"": 8,\n""tp3"": 11,\n""tp4"": 16...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 15,\n ...","{tp1: 5, tp2: 10, tp3: 22, tp4: -1, tp5: 30, s...","{tp1: 1.0, tp2: 4.0, tp3: 15.0, tp4: 22.0, tp5..."
3,12239338,"```\n{\n""tp1"": 5,\n""tp2"": 10,\n""tp3"": 11,\n""tp...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 21,\n ...","```json\n{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3""...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 1...","{\n ""tp1"": 4,\n ""tp2"": 6,\n ""tp3"": 15...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 1...","{tp1: 5, tp2: 10, tp3: 22, tp4: 24, tp5: 28, s...","{tp1: 5, tp2: 10, tp3: 22, tp4: 24, tp5: 28, s..."
4,12737013,"{""tp1"": 2, ""tp2"": 6, ""tp3"": 14, ""tp4"": 15, ""tp...","{\n ""tp1"": 3,\n ""tp2"": 6,\n ""tp3"": 16,\n ""...","```json\n{\n ""tp1"": 2,\n ""tp2"": 6,\n ""tp3"":...","{\n ""tp1"": 2,\n ""tp2"": 6,\n ""tp3"": 11...","{\n ""tp1"": 1,\n ""tp2"": 6,\n ""tp3"": 7,...","{\n ""tp1"": 2,\n ""tp2"": 6,\n ""tp3"": 11,\n ""...","{tp1: 5, tp2: 6, tp3: 13, tp4: 14, tp5: 21, st...","{\n ""tp1"": 5,\n ""tp2"": 6,\n ""tp3"": 11,\n ""..."

In [3]:
# Get the first row as a Series
first_row = df.iloc[0]

# Print raw values from first row
print("Raw values from first row:")
first_row["deepseek-reasoner_output"]

Raw values from first row:

'{tp1: 5, tp2: 7, tp3: 13, tp4: 15, tp5: 24, story_arc: Man in a Hole}  \n\n### Explanation:  \n- **tp1 (Opportunity)**: Sentence 5 (Gabriela’s invitation) introduces the catalyst for Elena’s departure from her routine.  \n- **tp2 (Change of Plans)**: Sentence 7 (Elena decides to attend the party) defines her initial commitment to the new goal.  \n- **tp3 (Point of No Return)**: Sentence 13 (Elena connects the cult’s plan) forces her to act decisively.  \n- **tp4 (Major Setback)**: Sentence 15 (Gabriela dismisses Elena’s warnings) creates a barrier to resolving the conflict.  \n- **tp5 (Climax)**: Sentence 24 (escape from the mansion) resolves the main threat.  \n- **Story Arc**: *Man in a Hole* fits best: Elena enters danger (cult ritual), escapes, and grows stronger (friendship deepened, bravery discovered), though lingering shadows hint at unresolved tension.'

In [ ]:
# Extract clean JSON from llama3.1-405b and llama3.1-8b columns using regex
import re
from openai import AsyncOpenAI, OpenAI
import asyncio
async def clean_json_output(text):
    if not text or pd.isna(text):
        return None
        
    client = AsyncOpenAI(
        api_key="sk-f61b1867d71847c3a65e72c7cacb0fe7",
        base_url="https://api.deepseek.com"
    )
    
    # Try to extract clean JSON using OpenAI
    try:
        response = await client.chat.completions.create(
            model="deepseek-chat",
            messages=[{
                "role": "system", 
                "content": "You are a JSON cleaner. Extract and format the JSON object from the given text. Return only valid JSON. It should be in the raw format of {{tp1: ##.#, tp2: ##.#, tp3: ##.#, tp4: ##.#, tp5: ##.#, story_arc: <arc_name>}}"
            },
            {
                "role": "user",
                "content": f"Clean this text into valid JSON:\n{text}"
            }]
        )
        cleaned_json = response.choices[0].message.content
        # Remove any markdown code block markers
        cleaned_json = re.sub(r'```\w*\n?', '', cleaned_json)
        # Remove any leading/trailing whitespace
        cleaned_json = cleaned_json.strip()
        # Try to parse as JSON to validate and standardize format
        try:
            json_obj = json.loads(cleaned_json)
            cleaned_json = json.dumps(json_obj)
        except json.JSONDecodeError:
            # If JSON parsing fails, try to extract the JSON-like structure
            pattern = r'\{.*?\}'
            match = re.search(pattern, cleaned_json, re.DOTALL)
            if match:
                cleaned_json = match.group(0)
        print(cleaned_json)
        return cleaned_json
    except:
        return None
# Create new columns with cleaned JSON
# Only process first 5 rows
async def process_rows():
    df['llama3.1-405b-instruct-fp8_cleaned'] = await asyncio.gather(*[clean_json_output(text) for text in df['llama3.1-405b-instruct-fp8_output']])
    df['llama3.1-8b-instruct_cleaned'] = await asyncio.gather(*[clean_json_output(text) for text in df['llama3.1-8b-instruct_output']])
    df['llama3.3-70b-instruct-fp8_cleaned'] = await asyncio.gather(*[clean_json_output(text) for text in df['llama3.3-70b-instruct-fp8_output']])
    df['llama3.1-70b-instruct-fp8_cleaned'] = await asyncio.gather(*[clean_json_output(text) for text in df['llama3.1-70b-instruct-fp8_output']])
    df['llama3.2-3b-instruct_cleaned'] = await asyncio.gather(*[clean_json_output(text) for text in df['llama3.2-3b-instruct_output']])
    df['deepseek-reasoner_cleaned'] = await asyncio.gather(*[clean_json_output(text) for text in df['deepseek-reasoner_output']])
    df['hermes3-70b_cleaned'] = await asyncio.gather(*[clean_json_output(text) for text in df['hermes3-70b_output']])

# await process_rows()

In [4]:

import pandas as pd

# Load the cleaned evaluation data
df = pd.read_pickle('cleaned_eval_data.pkl')

In [12]:
# Import ground truth data
with open('../datasets/ground_truth.json', 'r') as f:
    ground_truth = json.load(f)

# Create a new DataFrame with the same structure as df
ground_truth_df = pd.DataFrame(ground_truth)[['narrative_id', 'turning_points', 'arc_label']]

# Combine turning_points and arc_label into a single JSON object
ground_truth_df["ground_truth"] = ground_truth_df.apply(lambda row: {
    **row["turning_points"],
    "story_arc": row["arc_label"]
}, axis=1)


# Drop the original columns since they're now combined
ground_truth_df = ground_truth_df[['narrative_id', 'ground_truth']]
# Merge the two DataFrames on the 'narrative_id' column
merged_df = pd.merge(df, ground_truth_df, on='narrative_id', how='inner')

merged_df

,narrative_id,llama3.1-405b-instruct-fp8_output,llama3.1-8b-instruct_output,llama3.3-70b-instruct-fp8_output,llama3.1-70b-instruct-fp8_output,llama3.2-3b-instruct_output,hermes3-405b_output,deepseek-reasoner_output,hermes3-70b_output,llama3.1-405b-instruct-fp8_cleaned,llama3.1-8b-instruct_cleaned,llama3.3-70b-instruct-fp8_cleaned,llama3.1-70b-instruct-fp8_cleaned,llama3.2-3b-instruct_cleaned,deepseek-reasoner_cleaned,hermes3-70b_cleaned,ground_truth
0,11194689,"```\n{\n ""tp1"": 3,\n ""tp2"": 7,\n ""tp3"": 13,...","```json\n{\n ""tp1"": 5,\n ""tp2"": 6,\n ""tp3"":...","```json\n{\n ""tp1"": 3,\n ""tp2"": 7,\n ""tp3"":...","{\n ""tp1"": 3,\n ""tp2"": 5,\n ""tp3"": 9,\n ""t...","{\n ""tp1"": 5,\n ""tp2"": 6,\n ""tp3"": 7,...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 21,\n ...","{tp1: 5, tp2: 7, tp3: 13, tp4: 15, tp5: 24, st...","{\n ""tp1"": 5,\n ""tp2"": 9,\n ""tp3"": 10,\n ""...","{""tp1"": 3, ""tp2"": 7, ""tp3"": 13, ""tp4"": 20, ""tp...","{""tp1"": 5, ""tp2"": 6, ""tp3"": 14, ""tp4"": 16, ""tp...","{""tp1"": 3, ""tp2"": 7, ""tp3"": 10, ""tp4"": 16, ""tp...","{""tp1"": 3, ""tp2"": 5, ""tp3"": 9, ""tp4"": 16, ""tp5...","{""tp1"": 5, ""tp2"": 6, ""tp3"": 7, ""tp4"": 15, ""tp5...","{""tp1"": 5, ""tp2"": 7, ""tp3"": 13, ""tp4"": 15, ""tp...","{""tp1"": 5, ""tp2"": 9, ""tp3"": 10, ""tp4"": 19, ""tp...","{'tp1': 5.0, 'tp2': 9.0, 'tp3': 14.0, 'tp4': 1..."
1,11436303,"```\n{\n ""tp1"": 5,\n ""tp2"": 18,\n ""tp3"": 21...","{ ""tp1"": 5, ""tp2"": 14, ""tp3"": 17, ""tp4"": 21, ""...","{tp1: 5, tp2: 8, tp3: 18, tp4: 21, tp5: 38, st...","{""tp1"": 5, ""tp2"": 18, ""tp3"": 20, ""tp4"": 21, ""t...","{\n ""tp1"": 1,\n ""tp2"": 4,\n ""tp3"": 13,\n ""...","{\n ""tp1"": 6,\n ""tp2"": 18,\n ""tp3"": 24,\n ...","{tp1: 7, tp2: 18, tp3: 24, tp4: 21, tp5: 38, s...","{\n ""tp1"": ""1"",\n ""tp2"": ""5"",\n ""tp3"": ""18""...","{""tp1"": 5, ""tp2"": 18, ""tp3"": 21, ""tp4"": 22, ""t...","{""tp1"": 5, ""tp2"": 14, ""tp3"": 17, ""tp4"": 21, ""t...","{""tp1"": 5, ""tp2"": 8, ""tp3"": 18, ""tp4"": 21, ""tp...","{""tp1"": 5, ""tp2"": 18, ""tp3"": 20, ""tp4"": 21, ""t...","{""tp1"": 1, ""tp2"": 4, ""tp3"": 13, ""tp4"": 21, ""tp...","{""tp1"": 7, ""tp2"": 18, ""tp3"": 24, ""tp4"": 21, ""t...","{""tp1"": 1.0, ""tp2"": 5.0, ""tp3"": 18.0, ""tp4"": 2...","{'tp1': 5.0, 'tp2': 12.5, 'tp3': 22.0, 'tp4': ..."
2,12084954,"```\n{\n""tp1"": 5,\n""tp2"": 10,\n""tp3"": 15,\n""tp...","{\n ""tp1"": 3.0, \n ""tp2"": 5.0, \n ""tp3"": 10...","```json\n{\n ""tp1"": 4,\n ""tp2"": 5,\n ""tp3"":...","{tp1: 5, tp2: 10, tp3: 15, tp4: 22, tp5: 24, s...","{\n""tp1"": 5,\n""tp2"": 8,\n""tp3"": 11,\n""tp4"": 16...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 15,\n ...","{tp1: 5, tp2: 10, tp3: 22, tp4: -1, tp5: 30, s...","{tp1: 1.0, tp2: 4.0, tp3: 15.0, tp4: 22.0, tp5...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 15, ""tp4"": null, ...","{""tp1"": 3.0, ""tp2"": 5.0, ""tp3"": 10.0, ""tp4"": 2...","{""tp1"": 4, ""tp2"": 5, ""tp3"": 10, ""tp4"": 22, ""tp...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 15, ""tp4"": 22, ""t...","{""tp1"": 5, ""tp2"": 8, ""tp3"": 11, ""tp4"": 16, ""tp...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 22, ""tp4"": -1, ""t...","{""tp1"": 1.0, ""tp2"": 4.0, ""tp3"": 15.0, ""tp4"": 2...","{'tp1': 5.0, 'tp2': 10.0, 'tp3': 15.0, 'tp4': ..."
3,12239338,"```\n{\n""tp1"": 5,\n""tp2"": 10,\n""tp3"": 11,\n""tp...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 21,\n ...","```json\n{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3""...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 1...","{\n ""tp1"": 4,\n ""tp2"": 6,\n ""tp3"": 15...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 1...","{tp1: 5, tp2: 10, tp3: 22, tp4: 24, tp5: 28, s...","{tp1: 5, tp2: 10, tp3: 22, tp4: 24, tp5: 28, s...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 11, ""tp4"": 24, ""t...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 21, ""tp4"": 24, ""t...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 16, ""tp4"": 24, ""t...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 16, ""tp4"": 24, ""t...","{""tp1"": 4, ""tp2"": 6, ""tp3"": 15, ""tp4"": 24, ""tp...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 22, ""tp4"": 24, ""t...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 22, ""tp4"": 24, ""t...","{'tp1': 5.0, 'tp2': 10.0, 'tp3': 16.0, 'tp4': ..."
4,12737013,"{""tp1"": 2, ""tp2"": 6, ""tp3"": 14, ""tp4"": 15, ""tp...","{\n ""tp1"": 3,\n ""tp2"": 6,\n ""tp3"": 16,\n ""...","```json\n{\n ""tp1"": 2,\n ""tp2"": 6,\n ""tp3"":...","{\n ""tp1"": 2,\n ""tp2"": 6,\n ""tp3"": 11...","{\n ""tp1"": 1,\n ""tp2"": 6,\n ""tp3"": 7,...","{\n ""tp1"": 2,\n ""tp2"": 6,\n ""tp3"": 11,\n ""...","{tp1: 5, tp2: 6, tp3: 13, tp4: 14, tp5: 21, st...","{\n ""tp1"": 5,\n ""tp2"": 6,\n ""tp3"": 11,\n ""...","{""tp1"": 2, ""tp2"": 6, ""tp3"": 14, ""tp4"": 15, ""tp...","{""tp1"": 3, ""tp2"": 6, ""tp3"": 16, ""tp4"": 14, ""tp...","{""tp1"": 2, ""tp2"": 6, ""tp3"": 11, ""tp4"": 14, ""tp...","{""tp1"": 2, ""tp2"": 6, ""tp3"": 11, ""tp4"": 14, ""tp...","{""tp1"": 1, ""tp2"": 6, ""tp3"": 7, ""tp4"": 13, ""tp5...","{""tp1"": 5, ""tp2"": 6, ""tp3"": 13, ""tp4"": 14, ""tp...","{""tp1"": 5, ""tp2"": 6, ""tp3"": 11, ""tp4"": 14, ""tp...","{'tp1': 2.0, 'tp2': 6.0, 'tp3': 13.0, 'tp4': 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,9865381,"```\n{\n ""tp1"": 5,\n ""tp2"": 9,\n ""tp3"": 14,...","{\n ""tp1"": 4,\n ""tp2"": 5,\n ""tp3"": 11,\n ""...","```json\n{\n ""tp1"": 5,\n ""tp2"": 9,\n ""tp3"":...","{tp1: 5, tp2: 5, tp3: 10, tp4: 16, tp5: 20, st...","{\n ""tp1"": 2,\n ""tp2"": 5,\n ""tp3"": 15...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 15,\n ...","{tp1: 5, tp2: 10, tp3: 15, tp4: 16, tp5: 20, s...","{\n ""tp1"": 5,\n ""tp2"": 10,\n ""tp3"": 14,\n ...","{""tp1"": 5, ""tp2"": 9, ""tp3"": 14, ""tp4"": 16, ""tp...","{""tp1"": 4, ""tp2"": 5, ""tp3"": 11, ""tp4"": 13, ""tp...","{""tp1"": 5, ""tp2"": 9, ""tp3"": 14, ""tp4"": 16, ""tp...","{""tp1"": 5, ""tp2"": 5, ""tp3"": 10, ""tp4"": 16, ""tp...","{""tp1"": 2, ""tp2"": 5, ""tp3"": 15, ""tp4"": 13, ""tp...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 15, ""tp4"": 16, ""t...","{""tp1"": 5, ""tp2"": 10, ""tp3"": 14, ""tp4"": 16, ""t...","{'tp1': 5.0, 'tp2': 9.0, 'tp3': 13.0, 'tp4': 1..."
435,9899893,"{\n""tp1"": 4,\n""tp2"": 22,\n""tp3"": 28,\n""tp4"": 2...","{\n ""tp1"": 4,\n ""tp2"": 24,\n ""tp3"": 28,\n ...","{tp1: 3, tp2: 22, tp3: 28, tp4: 25, tp5: 37, s...","{\n""tp1"": 3,\n""tp2"": 4,\n""tp3"": 28,\n""tp4"": 25...","{\n ""tp1"": 4,\n ""tp2"": 3,\n ""tp3"": 23,\n ""...","{\n ""tp1"": 4,\n ""tp2"": 22,\n ""tp3"": 2...","{tp1: 4, tp2: 13, tp3: 30, tp4: 33, tp5: 37, s...","{\n""tp1"": 3,\n""tp2"": 4,\n""tp3"": 28,\n""tp4"": 33...","{""tp1"": 4, ""tp2"": 22, ""tp3"": 28, ""tp4"": 25, ""t...","{""tp1"": 4, ""tp2"": 24, ""tp3"": 28, ""tp4"": 25, ""t...","{""tp1"": 3, ""tp2"": 22, ""tp3"": 28, ""tp4"": 25, ""t...","{""tp1"": 3, ""tp2"": 4, ""tp3"": 28, ""tp4"": 25, ""tp...","{""tp1"": 4, ""tp2"": 3, ""tp3"": 23, ""tp4"": 27, ""tp...","{""tp1"": 4, ""tp2"": 13, ""tp3"": 30, ""tp4"": 33, ""t...","{""tp1"": 3, ""tp2"": 4, ""tp3"": 28, ""tp4"": 33, ""tp...","{'tp1': 4.0, 'tp2': 13.0, 'tp3': 27.0, 'tp4': ..."
436,99611432,"```\n{\n ""tp1"": 2,\n ""tp2"": 8,\n ""tp3"": 11,...","{\n ""tp1"": 2,\n ""tp2"": 6,\n ""tp3"": 8,\n ""t...","```json\n{\n ""tp1"": 2,\n ""tp2"": 3,\n ""tp3"":...","{tp1: 2, tp2: 4, tp3: 10, tp4: 15, tp5: 24, st...","{""tp1"": 2, ""tp2"": 4, ""tp3"": 16, ""tp4"": 9, ""tp5...","{\n ""tp1"": 2,\n ""tp2"": 3,\n ""tp3"": 11,\n ""...","{tp1: 3, tp2: 11, tp3: 19, tp4: 3, tp5: 24, st...","{\n ""tp1"": 2,\n ""tp2"": 3,\n ""tp3"": 10,\n ""...","{""tp1"": 2, ""tp2"": 8, ""tp3"": 11, ""tp4"": 15, ""tp...","{""tp1"": 2, ""tp2"": 6, ""tp3"": 8, ""tp4"": 12, ""tp5...","{""tp1"": 2, ""tp2"": 3, ""tp3"": 10, ""tp4"": 16, ""tp...","{""tp1"": 2, ""tp2"": 4, ""tp3"": 10, ""tp4"": 15, ""tp...","{""tp1"": 2, ""tp2"": 4, ""tp3"": 16, ""tp4"": 9, ""tp5...","{""tp1"": 3, ""tp2"": 11, ""tp3"": 19, ""tp4"": 3, ""tp...","{""tp1"": 2, ""tp2"": 3, ""tp3"": 10, ""tp4"": 15, ""tp...","{'tp1': 3.0, 'tp2': 6.0, 'tp3': 11.0, 'tp4': 2..."
437,99776112,"```\n{\n ""tp1"": 3,\n ""tp2"": 9,\n ""tp3"": 12,...","```json\n{\n ""tp1"": ""3"",\n ""tp2"": ""9"",\n ""t...","```json\n{\n ""tp1"": 3,\n ""tp2"": 9,\n ""tp3"":...","{\n ""tp1"": 3,\n ""tp2"": 11,\n ""tp3"": 12,\n ...","{\n ""tp1"": 2,\n ""tp2"": 3,\n ""tp3"": 12...","{\n ""tp1"": 9,\n ""tp2"": 12,\n ""tp3"": 16,\n ...","{tp1: 9, tp2: 12, tp3: 16, tp4: 24, tp5: 29, s...","{\n ""tp1"": 3.0,\n ""tp2"": 9.0,\n ""tp3"": 12.0...","{""tp1"": 3, ""tp2"": 9, ""tp3"": 12, ""tp4"": 24, ""tp...","{""tp1"": 3.0, ""tp2"": 9.0, ""tp3"": 12.0, ""tp4"": 2...","{""tp1"": 3, ""tp2"": 9, ""tp3"": 16, ""tp4"": 24, ""tp...","{""tp1"": 3, ""tp2"": 11, ""tp3"": 12, ""tp4"": 24, ""t...","{""tp1"": 2, ""tp2"": 3, ""tp3"": 12, ""tp4"": 24, ""tp...","{""tp1"": 9, ""tp2"": 12, ""tp3"": 16, ""tp4"": 24, ""t...","{""tp1"": 3.0, ""tp2"": 9.0, ""tp3"": 12.0, ""tp4"": 2...","{'tp1': 3.0, 'tp2': 12.0, 'tp3': 19.0, 'tp4': ..."
438,99899271,"```\n{\n ""tp1"": 5,\n ""tp2"": 11,\n ""tp3"": 15...","```json\n{\n ""tp1"": 5,\n ""tp2"": 8,\n ""tp3"":...","{tp1: 5, tp2: 8, tp3: 11, tp4: 19, tp5: 28, st...","{tp1: 5, tp2: 8, tp3: 15, tp4: 20, tp5: 28, st...","{\n ""tp1"": 1,\n ""tp2"": 6,\n ""tp3"": 9,...","{\n ""tp1"": 5,\n ""tp2"": 11,\n ""tp3"": 22,\n ...","{tp1: 5.5, tp2: 9.9, tp3: 23.23, tp4: 20.20, t...","{\n ""tp1"": ""4"",\n ""tp2"": ""5"",\n ""tp3"": ""8"",...","{""tp1"": 5, ""tp2"": 11, ""tp3"": 15, ""tp4"": 18, ""t...","{""tp1"": 5, ""tp2"": 8, ""tp3"": 11, ""tp4"": 17, ""tp...","{""tp1"": 5, ""tp2"": 8, ""tp3"": 11, ""tp4"": 19, ""tp...","{""tp1"": 5, ""tp2"": 8, ""tp3"": 15, ""tp4"": 20, ""tp...","{""tp1"": 1, ""tp2"": 6, ""tp3"": 9, ""tp4"": 14, ""tp5...","{""tp1"": 5.5, ""tp2"": 9.9, ""tp3"": 23.23, ""tp4"": ...","{""tp1"": 4.0, ""tp2"": 5.0, ""tp3"": 8.0, ""tp4"": 16...","{'tp1': 3.0, 'tp2': 7.0, 'tp3': 23.0, 'tp4': 2..."

In [14]:
# Save the merged data to a pickle file
merged_df.to_pickle('merged_eval_data.pkl')